# Generated by Django 5.2 on 2025-04-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textutils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('extra_space', models.BooleanField(default=False)),
                ('count', models.BooleanField(default=False)),
                ('uppercase', models.BooleanField(default=False)),
            ],
        ),
    ]
